/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package poo_restaurante;

import javax.swing.JOptionPane;

/**
 *
 * @author cphyros
 */
public class Menu extends javax.swing.JFrame { //Herencia

    IngresarC form1;
    IngresarD form3;// Asociacion Composicion
    IngresarT form5;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        form1 = new IngresarC();
        form3 = new IngresarD(form1);
        form5 = new IngresarT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        BG = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        GestionarCliyDev = new javax.swing.JMenu();
        IngresarCliente = new javax.swing.JMenuItem();
        ListadoDeClientes = new javax.swing.JMenuItem();
        BuscarCliente = new javax.swing.JMenuItem();
        GestionarVen = new javax.swing.JMenu();
        IngresarTrabajador = new javax.swing.JMenuItem();
        ListarTrab = new javax.swing.JMenuItem();
        BuscarTrab = new javax.swing.JMenuItem();
        ListarTXP = new javax.swing.JMenuItem();
        GestionarPed = new javax.swing.JMenu();
        IngresarPedido = new javax.swing.JMenuItem();
        ListadoDePedi = new javax.swing.JMenuItem();
        ListarPedporClie = new javax.swing.JMenuItem();
        ListadoPenT = new javax.swing.JMenuItem();
        BuscarPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 248, 241));

        desktopPane.setBackground(new java.awt.Color(251, 248, 241));

        BG.setBackground(new java.awt.Color(145, 31, 39));

        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenés/burgerwings.png"))); // NOI18N
        LOGO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 68)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 206, 127));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dear Burger");

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        desktopPane.setLayer(BG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GestionarCliyDev.setForeground(new java.awt.Color(102, 102, 102));
        GestionarCliyDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenés/delivery-man.png"))); // NOI18N
        GestionarCliyDev.setText("Gestionar Cliente y Delivery");
        GestionarCliyDev.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        IngresarCliente.setText("Ingresar Cliente");
        IngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarClienteActionPerformed(evt);
            }
        });
        GestionarCliyDev.add(IngresarCliente);

        ListadoDeClientes.setText("Listado de Clientes");
        ListadoDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoDeClientesActionPerformed(evt);
            }
        });
        GestionarCliyDev.add(ListadoDeClientes);

        BuscarCliente.setText("Buscar Cliente");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });
        GestionarCliyDev.add(BuscarCliente);

        menuBar.add(GestionarCliyDev);

        GestionarVen.setForeground(new java.awt.Color(102, 102, 102));
        GestionarVen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenés/waiter.png"))); // NOI18N
        GestionarVen.setText("Gestionar Trabajadores");
        GestionarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionarVenActionPerformed(evt);
            }
        });

        IngresarTrabajador.setText("Ingresar Trabajador");
        IngresarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarTrabajadorActionPerformed(evt);
            }
        });
        GestionarVen.add(IngresarTrabajador);

        ListarTrab.setText("Listar Trabajadores");
        ListarTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTrabActionPerformed(evt);
            }
        });
        GestionarVen.add(ListarTrab);

        BuscarTrab.setText("Buscar Trabajador");
        BuscarTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTrabActionPerformed(evt);
            }
        });
        GestionarVen.add(BuscarTrab);

        ListarTXP.setText("Listar Trabajadores por Puesto");
        ListarTXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTXPActionPerformed(evt);
            }
        });
        GestionarVen.add(ListarTXP);

        menuBar.add(GestionarVen);

        GestionarPed.setForeground(new java.awt.Color(102, 102, 102));
        GestionarPed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenés/choices.png"))); // NOI18N
        GestionarPed.setText("Gestionar Pedidos");

        IngresarPedido.setText("Ingresar Pedido");
        IngresarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarPedidoActionPerformed(evt);
            }
        });
        GestionarPed.add(IngresarPedido);

        ListadoDePedi.setText("Listado de Pedidos");
        ListadoDePedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoDePediActionPerformed(evt);
            }
        });
        GestionarPed.add(ListadoDePedi);

        ListarPedporClie.setText("Listar Pedidos por Cliente");
        ListarPedporClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPedporClieActionPerformed(evt);
            }
        });
        GestionarPed.add(ListarPedporClie);

        ListadoPenT.setText("Listado de Pedido en Tabla");
        ListadoPenT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoPenTActionPerformed(evt);
            }
        });
        GestionarPed.add(ListadoPenT);

        BuscarPedido.setText("Buscar Pedido");
        BuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPedidoActionPerformed(evt);
            }
        });
        GestionarPed.add(BuscarPedido);

        menuBar.add(GestionarPed);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarClienteActionPerformed
        desktopPane.add(form1);
        form1.setVisible(true);
    }//GEN-LAST:event_IngresarClienteActionPerformed

    private void IngresarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarPedidoActionPerformed
        if (form1.cont > 0) {
            form3 = new IngresarD(form1);
            desktopPane.add(form3);
            form3.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese cliente primero");
        }
    }//GEN-LAST:event_IngresarPedidoActionPerformed

    private void ListadoDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoDeClientesActionPerformed
        // TODO add your handling code here:
        if (form1.cont > 0) {
            String info = form1.listarClientes();
            ListarC form2 = new ListarC(info); // Dependencia
            desktopPane.add(form2);
            form2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay información disponible de clientes");
        }
    }//GEN-LAST:event_ListadoDeClientesActionPerformed

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
        if (form1.cont > 0) {
            BuscarC form2 = new BuscarC(form1);
            desktopPane.add(form2);
            form2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No ay información para buscar");
        }
    }//GEN-LAST:event_BuscarClienteActionPerformed

    private void ListadoDePediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoDePediActionPerformed
        // TODO add your handling code here:
        if (form3.cont > 0) {
            String info = form3.listarDeliverys();
            ListarD form4 = new ListarD(info);
            desktopPane.add(form4);
            form4.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay información disponible de delivery");
        }
    }//GEN-LAST:event_ListadoDePediActionPerformed

    private void BuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPedidoActionPerformed
        // TODO add your handling code here:
        if (form3.cont > 0) {
            BuscarD form2 = new BuscarD(form3);
            desktopPane.add(form2);
            form2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay informacion para buscar");
        }
    }//GEN-LAST:event_BuscarPedidoActionPerformed

    private void ListadoPenTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoPenTActionPerformed
        // TODO add your handling code here:
        if (form3.cont > 0) {
            ListarPedidos2 form4 = new ListarPedidos2(form3);
            desktopPane.add(form4);
            form4.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay información disponible de delivery");
        }
    }//GEN-LAST:event_ListadoPenTActionPerformed

    private void ListarPedporClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPedporClieActionPerformed
        // TODO add your handling code here:
        if (form1.cont > 0) {
            ListarXC form4 = new ListarXC(form3);
            desktopPane.add(form4);
            form4.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay información disponible");
        }
    }//GEN-LAST:event_ListarPedporClieActionPerformed

    private void GestionarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GestionarVenActionPerformed

    private void IngresarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarTrabajadorActionPerformed
        // TODO add your handling code here:
        desktopPane.add(form5);
        form5.setVisible(true);
    }//GEN-LAST:event_IngresarTrabajadorActionPerformed

    private void ListarTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTrabActionPerformed
        // TODO add your handling code here:
        if (form5.cont > 0) {
            ListarTrabajadores form2 = new ListarTrabajadores(form5); // Dependencia
            desktopPane.add(form2);
            form2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay información disponible de trabajadores");
        }
    }//GEN-LAST:event_ListarTrabActionPerformed

    private void BuscarTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTrabActionPerformed
        // TODO add your handling code here:
        if (form5.cont > 0) {
            BuscarT form2 = new BuscarT(form5);
            desktopPane.add(form2);
            form2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No ay información para buscar");
        }
    }//GEN-LAST:event_BuscarTrabActionPerformed

    private void ListarTXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTXPActionPerformed
        // TODO add your handling code here:
        if (form5.cont > 0) {
            ListarXP form4 = new ListarXP(form5);
            desktopPane.add(form4);
            form4.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay información disponible");
        }
    }//GEN-LAST:event_ListarTXPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BG;
    public javax.swing.JMenuItem BuscarCliente;
    public javax.swing.JMenuItem BuscarPedido;
    public javax.swing.JMenuItem BuscarTrab;
    public javax.swing.JMenu GestionarCliyDev;
    public javax.swing.JMenu GestionarPed;
    public javax.swing.JMenu GestionarVen;
    public javax.swing.JMenuItem IngresarCliente;
    public javax.swing.JMenuItem IngresarPedido;
    public javax.swing.JMenuItem IngresarTrabajador;
    public javax.swing.JLabel LOGO;
    public javax.swing.JMenuItem ListadoDeClientes;
    public javax.swing.JMenuItem ListadoDePedi;
    public javax.swing.JMenuItem ListadoPenT;
    public javax.swing.JMenuItem ListarPedporClie;
    public javax.swing.JMenuItem ListarTXP;
    public javax.swing.JMenuItem ListarTrab;
    public javax.swing.JDesktopPane desktopPane;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
